apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgetrace-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.forgetrace.com
    - api.forgetrace.com
    - www.forgetrace.pro
    - api.forgetrace.pro
    secretName: forgetrace-tls
  rules:
  - host: app.forgetrace.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgetrace-frontend
            port:
              number: 80
  - host: api.forgetrace.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgetrace-backend
            port:
              number: 8000
  - host: www.forgetrace.pro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgetrace-frontend
            port:
              number: 80
  - host: api.forgetrace.pro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgetrace-backend
            port:
              number: 8000
